server:
  port: 8081
  servlet:
    context-path: /FreshCart
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      use-suffix-pattern: false
    view:
      suffix: ''  # Loại bỏ suffix mặc định
    thymeleaf:
      cache: false
      suffix: .html
      mode: HTML
      servlet:
        content-type: text/html
  datasource:
    url: jdbc:mysql://localhost:3306/freshcartdb
    username: root
    password: 123456
    #hikari:
    #minimum-idle: 1
    #maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 15810287815-pnbp1aglg9h4ucdto6fa46uobrmlr1lc.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1196353608101950
            client-secret: 0c74626294c82d7f17d3993657cd8f95
            scope:
              - email
              - public_profile
